### ISSUE TITLE
Great project, is it possible to port the camera stuff to openpilot?

### ISSUE THREAD

**Issue by 0312birdzhang** [mob9221/vision-radar#12]
I want use webcam + openpilot running on ubuntu, but i'm confused on how to port, as they use visionipc, it's hard to learn.

**Comment by alamo3** [comment]
It was possible with older versions of openpilot so you could just clone an older release, newer releases need some worj. I'll take a look at what changed

**Comment by 0312birdzhang** [comment]
As openpilot already did it, so i will close tihis feature request.
